/*
 * These antags are hidden from the antags list in the antags tab of the preferences thing
 *
 * Certain midrunds are also hidden, disabled in the .ts files cus theres no associated datum
 * they are:
 * - OperativeMidround
 * - ClownoOperativeMidround
 * - SpaceNinja
 * - and a bunch others
 *
 * whatever this thing doesnt work, just move the antag .ts fules out of the project.
 *  */
GLOBAL_LIST_INIT(disabled_antags, list(
	ROLE_ABDUCTOR                   = TRUE,
	ROLE_ALIEN                      = TRUE,
	ROLE_ANCIENT_CREW               = TRUE,
	ROLE_ANOMALY_GHOST              = TRUE,
	ROLE_ASHWALKER                  = TRUE,
	ROLE_BATTLECRUISER_CAPTAIN      = TRUE,
	ROLE_BATTLECRUISER_CREW         = TRUE,
	ROLE_BEACH_BUM                  = TRUE,
	ROLE_BLOB_INFECTION             = TRUE,
	ROLE_BLOB                       = TRUE,
	ROLE_BLOOD_WORM_INFESTATION     = TRUE,
	ROLE_BLOOD_WORM                 = TRUE,
	ROLE_BRAINWASHED                = TRUE,
	ROLE_BROTHER                    = TRUE,
	ROLE_CHANGELING_MIDROUND        = TRUE,
	ROLE_CHANGELING                 = TRUE,
	ROLE_CLOWN_OPERATIVE_MIDROUND   = TRUE,
	ROLE_CLOWN_OPERATIVE            = TRUE,
	ROLE_CONTRACTOR_SUPPORT         = TRUE,
	ROLE_CULTIST                    = TRUE,
	ROLE_CYBER_POLICE               = TRUE,
	ROLE_DEATHSQUAD                 = TRUE,
	ROLE_DERELICT_DRONE             = TRUE,
	ROLE_DRONE                      = TRUE,
	ROLE_EMAGGED_BOT                = TRUE,
	ROLE_ESCAPED_PRISONER           = TRUE,
	ROLE_EVIL_CLONE                 = TRUE,
	ROLE_EXILE                      = TRUE,
	ROLE_FREE_BLOB                  = TRUE,
	ROLE_FUGITIVE_HUNTER            = TRUE,
	ROLE_FUGITIVE                   = TRUE,
	ROLE_GHOST_ROLE                 = TRUE,
	ROLE_GLITCH                     = TRUE,
	ROLE_HERETIC                    = TRUE,
	ROLE_HERMIT                     = TRUE,
	ROLE_HIVE                       = TRUE,
	ROLE_HOTEL_STAFF                = TRUE,
	ROLE_HYPNOTIZED                 = TRUE,
	ROLE_LAVALAND_SYNDICATE         = TRUE,
	ROLE_LAVALAND                   = TRUE,
	ROLE_LAZARUS_BAD                = TRUE,
	ROLE_LAZARUS_GOOD               = TRUE,
	ROLE_LIFEBRINGER                = TRUE,
	ROLE_LONE_OPERATIVE             = TRUE,
	ROLE_MALF_MIDROUND              = TRUE,
	ROLE_MALF                       = TRUE,
	ROLE_MORPH                      = TRUE,
	ROLE_NIGHTMARE                  = TRUE,
	ROLE_NINJA                      = TRUE,
	ROLE_OBSESSED                   = TRUE,
	ROLE_OPERATIVE_MIDROUND         = TRUE,
	ROLE_OPERATIVE_OVERWATCH        = TRUE,
	ROLE_OPERATIVE                  = TRUE,
	ROLE_OVERTHROW                  = TRUE,
	ROLE_PARADOX_CLONE              = TRUE,
	ROLE_POSIBRAIN                  = TRUE,
	ROLE_POSITRONIC_BRAIN           = TRUE,
	ROLE_PROVOCATEUR                = TRUE,
	ROLE_PYROCLASTIC_SLIME          = TRUE,
	ROLE_RECOVERED_CREW             = TRUE,
	ROLE_REV_HEAD                   = TRUE,
	ROLE_REV                        = TRUE,
	ROLE_REVENANT                   = TRUE,
	ROLE_SANTA                      = TRUE,
	ROLE_SLAUGHTER_DEMON            = TRUE,
	ROLE_SLEEPER_AGENT              = TRUE,
	ROLE_SOULTRAPPED_HERETIC        = TRUE,
	ROLE_SPACE_BAR_PATRON           = TRUE,
	ROLE_SPACE_BARTENDER            = TRUE,
	ROLE_SPACE_DOCTOR               = TRUE,
	ROLE_SPACE_DRAGON               = TRUE,
	ROLE_SPACE_PIRATE               = TRUE,
	ROLE_SPACE_SYNDICATE            = TRUE,
	ROLE_SPIDER                     = TRUE,
	ROLE_SPY                        = TRUE,
	ROLE_STOWAWAY_CHANGELING        = TRUE,
	ROLE_SUNWALKER                  = TRUE,
	ROLE_SYNDICATE_ASSAULTBORG      = TRUE,
	ROLE_SYNDICATE_CYBERSUN_CAPTAIN = TRUE,
	ROLE_SYNDICATE_CYBERSUN         = TRUE,
	ROLE_SYNDICATE_DRONE            = TRUE,
	ROLE_SYNDICATE_INFILTRATOR      = TRUE,
	ROLE_SYNDICATE_MEDBORG          = TRUE,
	ROLE_SYNDICATE_MONKEY           = TRUE,
	ROLE_SYNDICATE_SABOBORG         = TRUE,
	ROLE_SYNDICATE                  = TRUE,
	ROLE_TRAITOR                    = TRUE,
	ROLE_VENUSHUMANTRAP             = TRUE,
	ROLE_VOIDWALKER                 = TRUE,
	ROLE_WIZARD_APPRENTICE          = TRUE,
	ROLE_WIZARD_MIDROUND            = TRUE,
	ROLE_WIZARD                     = TRUE,
	ROLE_ZOMBIE                     = TRUE,
	ROLE_CYBER_TAC                  = TRUE,
	ROLE_NETGUARDIAN                = TRUE,
))

// GLOBAL_LIST_INIT(disabled_antags, list(
// 	/datum/antagonist/abductor,
// 	/datum/antagonist/bitrunning_glitch,
// 	/datum/antagonist/blob,
// 	/datum/antagonist/blob/infection,
// 	/datum/antagonist/blood_worm,
// 	/datum/antagonist/blood_worm/infestation,
// 	/datum/antagonist/bloodsucker,
// 	/datum/antagonist/brother,
// 	/datum/antagonist/changeling,
// 	/datum/antagonist/changeling/space,
// 	/datum/antagonist/cortical_borer,
// 	/datum/antagonist/cult,
// 	/datum/antagonist/heretic,
// 	/datum/antagonist/infected_ipc,
// 	/datum/antagonist/malf_ai,
// 	/datum/antagonist/nightmare,
// 	/datum/antagonist/ninja,
// 	/datum/antagonist/nukeop,
// 	/datum/antagonist/nukeop/clownop,
// 	/datum/antagonist/nukeop/lone,
// 	/datum/antagonist/obsessed,
// 	/datum/antagonist/paradox_clone,
// 	/datum/antagonist/rev,
// 	/datum/antagonist/rev/head,
// 	/datum/antagonist/revenant,
// 	/datum/antagonist/space_dragon,
// 	/datum/antagonist/spy,
// 	/datum/antagonist/traitor,
// 	/datum/antagonist/voidwalker,
// 	/datum/antagonist/wizard,
// 	/datum/antagonist/xeno,
// ))

