/**
 * This unit test tests underwear items in the game, and makes sure each legacy sprite item corresponds to an underwear item.
 * However it isnt a unit test, cus i cant figure out how to run em on vsc, so now its an admin command instead.
 * Okay its explained how to do the unit test in the file, but that wont stop me cus i cant read
 * also admin verb is easier
 */
ADMIN_VERB(rebuild_underwear, R_DEBUG, "Rebuild Underwear", "Regenerate underwear item files.", ADMIN_CATEGORY_DEBUG)
	var/doit = alert(
		usr,
		"Hi! This command is only useful if you are on a local, non-live, development environment. \
		Basically if youre on a live server, this command is pointless and shouldnt be used! \
		\n\n\
		So anyway it autopopulates the wierd undie item files for you automatically.\
		Continue? \
		\n\n\
		BTW if you know how to run a unit test from VSC, let me know at 1-800-IM-CODER",
		"Now hold up a sec!",
		"Yes continue, im on a local server",
		"Oops im on the live server, nevermind"
		)
	if(doit != "Yes continue, im on a local server")
		return
	message_admins("Underwear rebuild command initiated by [usr], if this is a live server, please ridicule them!")
	var/starttime = world.time
	var/datum/panty_raider/PR = new()
	PR.raid_panties()
	QDEL_NULL(PR)
	var/timetook = DisplayTimeText(world.time - starttime)
	message_admins("Underwear rebuild command completed by [usr]! Time taken: [timetook].")
	message_admins("Check ur source control for if it actually did anything ♥.")

/// Performs the regeneration of underwear item files for local dev stuff
/datum/panty_raider
	var/list/sprites_to_items_names = list(
		/datum/sprite_accessory/underwear = "BRIEFS",
		/datum/sprite_accessory/undershirt = "SHIRT",
		/datum/sprite_accessory/bra = "BRA",
		/datum/sprite_accessory/socks = "SOCKS"
	)

	var/list/outputs = list(
		briefs = list(),
		shirt = list(),
		socks = list()
	)

	var/list/files_by_type = list( // thanks linux for not using the gosh darned root directory
		briefs = 'modular_zzplurt/code/modules/clothing/underwear/~generated_files/briefs.dm',
		shirt = 'modular_zzplurt/code/modules/clothing/underwear/~generated_files/shirt.dm',
		socks = 'modular_zzplurt/code/modules/clothing/underwear/~generated_files/socks.dm'
	)

/datum/panty_raider/proc/raid_panties()
	outputs["briefs"] = generate_objects_file(/datum/sprite_accessory/underwear)
	outputs["shirt"] = generate_objects_file(/datum/sprite_accessory/undershirt) + generate_objects_file(/datum/sprite_accessory/bra, FALSE)
	outputs["socks"] = generate_objects_file(/datum/sprite_accessory/socks)

	var/fail = FALSE
	for(var/object_type in outputs)
		var/list/lines = outputs[object_type]
		var/output_file = "[lines.Join("\n")]"
		rustg_file_write(output_file, "modular_zzplurt/code/modules/clothing/underwear/~generated_files/[object_type].dm")
		var/current = file2text(files_by_type[object_type])
		if(current != output_file)
			message_admins("[files_by_type[object_type]] is out of date.")
			fail = TRUE

	if(fail)
		message_admins("Underwear items generated files are out of date. Check your source control for updates.")
		// TEST_FAIL("Underwear items generated files are out of date. Run locally by enabling unit tests, (see _compile_options.dm) and copy 'data/~generated_files' to 'modular_zzplurt/code/modules/clothing/underwear/~generated_files'")

/datum/panty_raider/proc/generate_objects_file(datum/sprite_accessory/sprite_type, header = TRUE)
	var/clothing_name = sprites_to_items_names[sprite_type]

	var/list/output = list()
	if(header)
		output += "/* This file is automatically generated by the unit test. Do not edit it manually, use the [LOWER_TEXT(clothing_name)]_edits.dm file instead."
		output += " * Generating this file is done by running the unit test locally, see the fail message for more details."
		output += " * All items corresponding to [sprite_type] should be here."
		output += " */"
	else
		output += "/// [LOWER_TEXT(clothing_name)] section"

	output += ""

	for(var/sprite in subtypesof(sprite_type))
		if(initial(sprite:from_object))
			continue
		var/sprite_name = "[sprite]"
		sprite_name = replacetext(sprite_name, regex("\\/datum\\/sprite_accessory\\/(underwear|undershirt|socks|bra)\\/"), "")
		output += "[clothing_name]_FROM_SPRITE_ACCESSORY([sprite_name])"

	output += ""

	return output

