/// HEY FUZZY, PUT THE KEYS HERE
#define DOAFTER_EXAMPLE "DOAFTER_EXAMPLE"
#define DOAFTER_LAY_CABLE "DOAFTER_LAY_CABLE"
#define DOAFTER_CUTTING_CABLE "DOAFTER_CUTTING_CABLE"
#define DOAFTER_PRYING_FLOORTILE "DOAFTER_PRYING_FLOORTILE"
#define DOAFTER_TAKE_CLOTHES_OFF "DOAFTER_TAKE_CLOTHES_OFF"
#define DOAFTER_USE_HEALTH_ANALYZER "DOAFTER_USE_HEALTH_ANALYZER"
#define DOAFTER_USE_HEALTH_ANALYZER_CHEM "DOAFTER_USE_HEALTH_ANALYZER_CHEM"

/// single-line ez_doafter that returns on failure
#define EZ_DOAFTER_RETURN_ON_FAIL(doer, target, baroverride, kind)\
if(!ez_doafter(doer, target, baroverride, kind)){\
	return;\
}
