#define CSNIP_TEMPERAMENT        "Temperment"
#define CSNIP_BUILD              "Build"
#define CSNIP_BACKGROUND         "Background"
#define CSNIP_EARLY_BACKGROUND   "Early Background"
#define CSNIP_ADULT_BACKGROUND   "Adult Background"

#define CSNIP_TAB_PARENTS        "Family: Parents"
#define CSNIP_TAB_SIBLINGS       "Family: Siblings"
#define CSNIP_TAB_PLANETS        "Homeworld: Origin"
#define CSNIP_TAB_CHILDHOOD      "Events: Childhood"
#define CSNIP_TAB_TEENAGE        "Events: Teenage"
#define CSNIP_TAB_RELATIONSHIPS  "History: Relationships"
#define CSNIP_TAB_CRIMES         "History: Criminal"
#define CSNIP_TAB_EDUCATION      "History: Education"
#define CSNIP_TAB_WORK           "History: Work"
#define CSNIP_TAB_MILITARY       "History: Military"
#define CSNIP_TAB_MEDICAL        "History: Medical"
#define CSNIP_TAB_ECONOMY        "Status: Economy"
#define CSNIP_TAB_SOCIAL         "Status: Social"
#define CSNIP_TAB_BELIEFS        "Personal: Beliefs"
#define CSNIP_TAB_DISASTER       "Events: Disaster"
#define CSNIP_TAB_SECRETS        "Personal: Secrets"
