export type VCDataPack = {
  saymode_data: VCSaymodeData;
  message_data: VCMessageData;
};

export type VCSaymodeData = {
  saymode: string;
  custom: boolean;
  invoke_token: string;
  settings: VCSettingDataPack;
};

export type VCSettingData = {
  path: string;
  key: string;
  value: any; // just trust me bro
  kind: string;
  name: string;
  min: number;
  max: number;
  choices: unknown[];
  category: string;
  subgroup: string;
};

export type VCMessageData = {
  body_text: string;
  body_spans: string;
  used_verb: string;
  is_radio: boolean;
  is_emote: boolean;
  is_emote_quick: boolean;
  am_ghost: boolean;
  displayed_name: string;
  radio_color: string;
  radio_freq_name: string;
  language_icon: string;
  language_understood: boolean;
  ghost_link: string;
  body_span_class: string;
  body_span_color: string;
  msg_splice_timeout: number;
  msg_splice_last_saymode: string;
};

export type VCSettingDataPack = {
  message_background_color: VCSettingData;
  message_background_grad_angle: VCSettingData;
  message_background_grad_end: VCSettingData;
  message_background_grad_start: VCSettingData;
  message_background_grad_use: VCSettingData;
  message_background_image: VCSettingData;
  message_background_img_opacity: VCSettingData;
  message_background_opacity: VCSettingData;
  message_background_padding_bottom: VCSettingData;
  message_background_padding_left: VCSettingData;
  message_background_padding_right: VCSettingData;
  message_background_padding_top: VCSettingData;
  message_border_color: VCSettingData;
  message_border_radius: VCSettingData;
  message_border_style: VCSettingData;
  message_border_width: VCSettingData;
  message_show: VCSettingData;
  message_text_align: VCSettingData;
  message_text_color: VCSettingData;
  message_text_decoration: VCSettingData;
  message_text_font: VCSettingData;
  message_text_letter_spacing: VCSettingData;
  message_text_line_height: VCSettingData;
  message_text_opacity: VCSettingData;
  message_text_padding_bottom: VCSettingData;
  message_text_padding_left: VCSettingData;
  message_text_padding_right: VCSettingData;
  message_text_padding_top: VCSettingData;
  message_text_shadow_blur: VCSettingData;
  message_text_shadow_blur2: VCSettingData;
  message_text_shadow_color: VCSettingData;
  message_text_shadow_color2: VCSettingData;
  message_text_shadow_offset_x: VCSettingData;
  message_text_shadow_offset_x2: VCSettingData;
  message_text_shadow_offset_y: VCSettingData;
  message_text_shadow_offset_y2: VCSettingData;
  message_text_shadow_use: VCSettingData;
  message_text_shadow_use2: VCSettingData;
  message_text_size: VCSettingData;
  message_text_transform: VCSettingData;
  message_text_word_spacing: VCSettingData;

  name_background_color: VCSettingData;
  name_background_grad_angle: VCSettingData;
  name_background_grad_end: VCSettingData;
  name_background_grad_start: VCSettingData;
  name_background_grad_use: VCSettingData;
  name_background_image: VCSettingData;
  name_background_img_opacity: VCSettingData;
  name_background_opacity: VCSettingData;
  name_background_padding_bottom: VCSettingData;
  name_background_padding_left: VCSettingData;
  name_background_padding_right: VCSettingData;
  name_background_padding_top: VCSettingData;
  name_border_color: VCSettingData;
  name_border_radius: VCSettingData;
  name_border_style: VCSettingData;
  name_border_width: VCSettingData;
  name_show: VCSettingData;
  name_text_align: VCSettingData;
  name_text_color: VCSettingData;
  name_text_decoration: VCSettingData;
  name_text_font: VCSettingData;
  name_text_letter_spacing: VCSettingData;
  name_text_line_height: VCSettingData;
  name_text_opacity: VCSettingData;
  name_text_padding_bottom: VCSettingData;
  name_text_padding_left: VCSettingData;
  name_text_padding_right: VCSettingData;
  name_text_padding_top: VCSettingData;
  name_text_shadow_blur: VCSettingData;
  name_text_shadow_blur2: VCSettingData;
  name_text_shadow_color: VCSettingData;
  name_text_shadow_color2: VCSettingData;
  name_text_shadow_offset_x: VCSettingData;
  name_text_shadow_offset_x2: VCSettingData;
  name_text_shadow_offset_y: VCSettingData;
  name_text_shadow_offset_y2: VCSettingData;
  name_text_shadow_use: VCSettingData;
  name_text_shadow_use2: VCSettingData;
  name_text_size: VCSettingData;
  name_text_transform: VCSettingData;
  name_text_word_spacing: VCSettingData;

  outer_box_background_color: VCSettingData;
  outer_box_background_grad_angle: VCSettingData;
  outer_box_background_grad_end: VCSettingData;
  outer_box_background_grad_start: VCSettingData;
  outer_box_background_grad_use: VCSettingData;
  outer_box_background_image: VCSettingData;
  outer_box_background_img_opacity: VCSettingData;
  outer_box_background_opacity: VCSettingData;
  outer_box_background_padding_bottom: VCSettingData;
  outer_box_background_padding_left: VCSettingData;
  outer_box_background_padding_right: VCSettingData;
  outer_box_background_padding_top: VCSettingData;
  outer_box_border_color: VCSettingData;
  outer_box_border_radius: VCSettingData;
  outer_box_border_style: VCSettingData;
  outer_box_border_width: VCSettingData;

  pfp_background_color: VCSettingData;
  pfp_background_grad_angle: VCSettingData;
  pfp_background_grad_end: VCSettingData;
  pfp_background_grad_start: VCSettingData;
  pfp_background_grad_use: VCSettingData;
  pfp_background_image: VCSettingData;
  pfp_background_img_opacity: VCSettingData;
  pfp_background_opacity: VCSettingData;
  pfp_background_padding_bottom: VCSettingData;
  pfp_background_padding_left: VCSettingData;
  pfp_background_padding_right: VCSettingData;
  pfp_background_padding_top: VCSettingData;
  pfp_border_color: VCSettingData;
  pfp_border_radius: VCSettingData;
  pfp_border_style: VCSettingData;
  pfp_border_width: VCSettingData;
  pfp_image_height: VCSettingData;
  pfp_image_link: VCSettingData;
  pfp_image_link_url_filename: VCSettingData;
  pfp_image_link_url_host: VCSettingData;
  pfp_image_opacity: VCSettingData;
  pfp_image_scaling: VCSettingData;
  pfp_image_shape: VCSettingData;
  pfp_image_width: VCSettingData;
  pfp_show: VCSettingData;

  preview_text: string;
};
