export type VCDataPack = {
  saymode_data: Record<string, VCSettingData>;
  message_data: VCMessageData;
};

export type VCSettingData = {
  path: string;
  key: string;
  value: string | number | boolean;
  kind: string;
  name: string;
  min: number;
  max: number;
  choices: unknown[];
  category: string;
  subgroup: string;
};

export type VCMessageData = {
  body_text: string;
  body_spans: string;
  used_verb: string;
  is_radio: boolean;
  is_emote: boolean;
  is_emote_quick: boolean;
  am_ghost: boolean;
  displayed_name: string;
  radio_color: string;
  radio_freq_name: string;
  language_icon: string;
  language_understood: boolean;
  ghost_link: string;
  body_span_class: string;
  body_span_color: string;
  msg_splice_timeout: number;
  msg_splice_last_saymode: string;
};

export type VCSettingDataPack = {
  message_background_color: VCSettingData;
  message_background_grad_angle: VCSettingData;
  message_background_grad_end: VCSettingData;
  message_background_grad_start: VCSettingData;
  message_background_grad_use: VCSettingData;
  message_background_image: VCSettingData;
  message_background_img_opacity: VCSettingData;
  message_background_opacity: VCSettingData;
  message_background_padding_bottom: VCSettingData;
  message_background_padding_left: VCSettingData;
  message_background_padding_right: VCSettingData;
  message_background_padding_top: VCSettingData;
  message_border_color: VCSettingData;
  message_border_radius: VCSettingData;
  message_border_style: VCSettingData;
  message_border_width: VCSettingData;
  message_show: VCSettingData;
  message_text_align: VCSettingData;
  message_text_color: VCSettingData;
  message_text_decoration: VCSettingData;
  message_text_font: VCSettingData;
  message_text_letter_spacing: VCSettingData;
  message_text_line_height: VCSettingData;
  message_text_opacity: VCSettingData;
  message_text_padding_bottom: VCSettingData;
  message_text_padding_left: VCSettingData;
  message_text_padding_right: VCSettingData;
  message_text_padding_top: VCSettingData;
  message_text_shadow_blur: VCSettingData;
  message_text_shadow_blur2: VCSettingData;
  message_text_shadow_color: VCSettingData;
  message_text_shadow_color2: VCSettingData;
  message_text_shadow_offset_x: VCSettingData;
  message_text_shadow_offset_x2: VCSettingData;
  message_text_shadow_offset_y: VCSettingData;
  message_text_shadow_offset_y2: VCSettingData;
  message_text_shadow_use: VCSettingData;
  message_text_shadow_use2: VCSettingData;
  message_text_size: VCSettingData;
  message_text_transform: VCSettingData;
  message_text_word_spacing: VCSettingData;

  name_background_color: string;
  name_background_grad_angle: number;
  name_background_grad_end: string;
  name_background_grad_start: string;
  name_background_grad_use: boolean;
  name_background_image: string;
  name_background_img_opacity: number;
  name_background_opacity: number;
  name_background_padding_bottom: number;
  name_background_padding_left: number;
  name_background_padding_right: number;
  name_background_padding_top: number;
  name_border_color: string;
  name_border_radius: number;
  name_border_style: string;
  name_border_width: number;
  name_show: boolean;
  name_text_align: string;
  name_text_color: string;
  name_text_decoration: string;
  name_text_font: string;
  name_text_letter_spacing: number;
  name_text_line_height: number;
  name_text_opacity: number;
  name_text_padding_bottom: number;
  name_text_padding_left: number;
  name_text_padding_right: number;
  name_text_padding_top: number;
  name_text_shadow_blur: number;
  name_text_shadow_blur2: number;
  name_text_shadow_color: string;
  name_text_shadow_color2: string;
  name_text_shadow_offset_x: number;
  name_text_shadow_offset_x2: number;
  name_text_shadow_offset_y: number;
  name_text_shadow_offset_y2: number;
  name_text_shadow_use: boolean;
  name_text_shadow_use2: boolean;
  name_text_size: number;
  name_text_transform: string;
  name_text_word_spacing: number;

  outer_box_background_color: string;
  outer_box_background_grad_angle: number;
  outer_box_background_grad_end: string;
  outer_box_background_grad_start: string;
  outer_box_background_grad_use: boolean;
  outer_box_background_image: string;
  outer_box_background_img_opacity: number;
  outer_box_background_opacity: number;
  outer_box_background_padding_bottom: number;
  outer_box_background_padding_left: number;
  outer_box_background_padding_right: number;
  outer_box_background_padding_top: number;
  outer_box_border_color: string;
  outer_box_border_radius: number;
  outer_box_border_style: string;
  outer_box_border_width: number;

  pfp_background_color: string;
  pfp_background_grad_angle: number;
  pfp_background_grad_end: string;
  pfp_background_grad_start: string;
  pfp_background_grad_use: boolean;
  pfp_background_image: string;
  pfp_background_img_opacity: number;
  pfp_background_opacity: number;
  pfp_background_padding_bottom: number;
  pfp_background_padding_left: number;
  pfp_background_padding_right: number;
  pfp_background_padding_top: number;
  pfp_border_color: string;
  pfp_border_radius: number;
  pfp_border_style: string;
  pfp_border_width: number;
  pfp_image_height: number;
  pfp_image_link: string;
  pfp_image_link_url_filename: string;
  pfp_image_link_url_host: string;
  pfp_image_opacity: number;
  pfp_image_scaling: number;
  pfp_image_shape: string;
  pfp_image_width: number;
  pfp_show: boolean;
  preview_text: string;
};
